"""
🎭 Behavioral Playwright (V10.0.0 - Quantum Edition)
Production-Grade Humanized Automation, Resilient Browser Orchestration & Self-Healing AI/CV
"""

from .ai import (
    ActionValidator,
    AIOrchestrator,
    LLMProvider,
    LLMProviderProtocol,
    LLMReasoning,
    OCREngine,
    SelfHealingResolver,
    VisionEngine,
    VisualDetector,
    VisualElement,
    VisualVerification,
)
from .behavior import (
    BehavioralHumanizer,
    LinguisticKeystrokeDynamics,
    SelfHealingSelectorEngine,
)
from .config import (
    AIConfig,
    AutomationConfig,
    BrowserConfig,
    ClickConfig,
    KeyboardConfig,
    LocaleConfig,
    MouseConfig,
    NetworkConfig,
    RenderingConfig,
)
from .diagnostics import (
    AmbientSensorSpoofEngine,
    AudioFingerprintDeflectionEngine,
    BiometricLivenessSynthesizer,
    CanvasGridMappingDriver,
    CognitiveInterferenceModel,
    EbpfTcpSpoofBridge,
    EnvironmentalTrustEngine,
    ExploitPoCExporter,
    ExtensionCanaryShieldEngine,
    FontMetricCalibrationEngine,
    HardwareAttestationRelay,
    JA4TlsHandshakeEmulator,
    JSEngineDivergenceEmulator,
    LocalOSInputBridge,
    MFAOtpPollingBridge,
    MockChallengeSolver,
    MultimodalTimingCorrelation,
    NativeCoreInterface,
    VirtualCpuCacheTimingJitter,
    WebWorkerEvasionEngine,
)
from .exceptions import (
    AutomationError,
    BrowserLaunchError,
    ConfigurationError,
    InteractionError,
    NavigationError,
    ProviderError,
)
from .math_engine import (
    AffineCoordinateMapper,
    BezierTrajectoryGenerator,
    LorenzAttractorGenerator,
    SigmaDriftTrajectoryGenerator,
)
from .navigation import (
    CircuitBreaker,
    CircuitState,
    MarkovLoopDetector,
    NavigationManager,
)
from .providers import (
    BrowserLifecycleManager,
    BrowserProviderFactory,
    CDPBrowserProvider,
    CloakBrowserProvider,
    MockBrowserProvider,
    PlaywrightProvider,
)
from .utils import (
    BrowserContextProtocol,
    BrowserProtocol,
    BrowserProvider,
    ChallengeSolverProtocol,
    Clock,
    DeterministicRandomSource,
    ElementHandleProtocol,
    KeyboardProtocol,
    MockBrowserContext,
    MockElement,
    MockKeyboard,
    MockMouse,
    MockPage,
    MouseProtocol,
    PageProtocol,
    RandomSource,
    SystemClock,
    SystemRandomSource,
    VirtualTestClock,
)

__version__ = "10.0.0"

__all__ = [
    # Config
    "AutomationConfig",
    "AIConfig",
    "BrowserConfig",
    "ClickConfig",
    "KeyboardConfig",
    "LocaleConfig",
    "MouseConfig",
    "NetworkConfig",
    "RenderingConfig",
    # Exceptions
    "AutomationError",
    "BrowserLaunchError",
    "ConfigurationError",
    "InteractionError",
    "NavigationError",
    "ProviderError",
    # Protocols & Abstractions
    "RandomSource",
    "Clock",
    "MouseProtocol",
    "KeyboardProtocol",
    "ElementHandleProtocol",
    "PageProtocol",
    "BrowserContextProtocol",
    "BrowserProtocol",
    "BrowserProvider",
    "ChallengeSolverProtocol",
    "LLMProviderProtocol",
    "SystemRandomSource",
    "DeterministicRandomSource",
    "SystemClock",
    "VirtualTestClock",
    # Mocks
    "MockMouse",
    "MockKeyboard",
    "MockElement",
    "MockPage",
    "MockBrowserContext",
    # Math Engine
    "BezierTrajectoryGenerator",
    "SigmaDriftTrajectoryGenerator",
    "LorenzAttractorGenerator",
    "AffineCoordinateMapper",
    # Diagnostics & Bridges
    "NativeCoreInterface",
    "CognitiveInterferenceModel",
    "EnvironmentalTrustEngine",
    "JA4TlsHandshakeEmulator",
    "MFAOtpPollingBridge",
    "LocalOSInputBridge",
    "JSEngineDivergenceEmulator",
    "WebWorkerEvasionEngine",
    "AmbientSensorSpoofEngine",
    "AudioFingerprintDeflectionEngine",
    "FontMetricCalibrationEngine",
    "ExtensionCanaryShieldEngine",
    "VirtualCpuCacheTimingJitter",
    "MultimodalTimingCorrelation",
    "EbpfTcpSpoofBridge",
    "BiometricLivenessSynthesizer",
    "HardwareAttestationRelay",
    "MockChallengeSolver",
    "CanvasGridMappingDriver",
    "ExploitPoCExporter",
    # Behavior
    "BehavioralHumanizer",
    "LinguisticKeystrokeDynamics",
    "SelfHealingSelectorEngine",
    # Navigation
    "CircuitState",
    "CircuitBreaker",
    "MarkovLoopDetector",
    "NavigationManager",
    # Providers
    "PlaywrightProvider",
    "CloakBrowserProvider",
    "CDPBrowserProvider",
    "MockBrowserProvider",
    "BrowserProviderFactory",
    "BrowserLifecycleManager",
    # AI & Self Healing
    "VisualElement",
    "OCREngine",
    "VisualDetector",
    "VisionEngine",
    "LLMProvider",
    "LLMReasoning",
    "SelfHealingResolver",
    "ActionValidator",
    "VisualVerification",
    "AIOrchestrator",
]
