"""Independent Verification Oracle for behavioral-playwright.

This oracle determines whether observed runtime behavior, returned dictionaries,
thrown exceptions, or execution traces satisfy documented engineering contracts.

CRITICAL INVARIANTS:
1. `dry_run_success` is NEVER classified as REAL_SUCCESS.
2. A swallowed exception is NEVER classified as REAL_SUCCESS.
3. Provider absence is explicitly classified as PROVIDER_UNAVAILABLE, not failure or fake success.
4. Mocks/doubles are explicitly classified as SIMULATION, never REAL_SUCCESS.
5. `CLAIMED_SUCCESS` without verified physical/browser evidence is NEVER `REAL_SUCCESS`.
6. Every `VERIFIED_REAL_SUCCESS` must satisfy the 7-pillar RuntimeEvidenceContract and be signed.
7. Only verdicts cryptographically sealed by this Oracle are trusted by the Master Gate.
"""
from __future__ import annotations

import enum
import hashlib
import hmac
import os
import time
import uuid
from dataclasses import dataclass, field
from pathlib import Path
from typing import Any, Callable, Dict, List, Optional, Set, Tuple

from harness.runtime_probe import ProvenanceError, RuntimeEvidence, TrustedRuntimeProbe


class ExecutionStatus(str, enum.Enum):
    """Rigorous classification taxonomy for execution outcomes."""
    CLAIMED_SUCCESS = "CLAIMED_SUCCESS"
    OBSERVED_SUCCESS = "OBSERVED_SUCCESS"
    VERIFIED_REAL_SUCCESS = "VERIFIED_REAL_SUCCESS"
    REAL_SUCCESS = "VERIFIED_REAL_SUCCESS"  # Strict alias: REAL_SUCCESS is VERIFIED_REAL_SUCCESS
    REAL_FAILURE = "REAL_FAILURE"
    DRY_RUN = "DRY_RUN"
    SIMULATION = "SIMULATION"
    PROVIDER_UNAVAILABLE = "PROVIDER_UNAVAILABLE"
    UNIMPLEMENTED = "UNIMPLEMENTED"
    PARTIAL = "PARTIAL"
    UNKNOWN = "UNKNOWN"


@dataclass
class OracleVerdict:
    """Detailed verdict issued by the Independent Oracle.

    Verdicts certifying VERIFIED_REAL_SUCCESS must carry a cryptographic seal
    generated by IndependentOracle._seal_verdict. Unsealed verdicts are rejected by the gate.
    """
    status: ExecutionStatus
    is_acceptable: bool
    reason: str
    evidence: Dict[str, Any]
    violations: List[str]
    execution_id: Optional[str] = None
    evidence_id: Optional[str] = None
    seal: Optional[str] = None


@dataclass
class RuntimeEvidenceContract:
    """Rigorous runtime evidence contract for VERIFIED_REAL_SUCCESS.

    Invariants:
    1. execution_id: Unique execution identifier bound to this operation.
    2. session_id: Explicit execution/session identity.
    3. execution_start_time: POSIX timestamp when operation started.
    4. execution_end_time: Optional POSIX timestamp when operation concluded.
    5. expected_url: Expected target URL verified against live page.
    6. expected_title: Expected page title substring verified against live page.
    7. required_artifacts: List of file paths required on disk.
    8. live_page: Optional active Playwright Page object.
    9. expected_dom_selector: DOM selector whose state change is verified in live DOM.
    10. expected_dom_text: Expected element text or attribute value.
    11. post_operation_verified: Boolean indicator (must be backed by probe observation).
    12. evidence: Optional cryptographically sealed RuntimeEvidence bundle from TrustedRuntimeProbe.
    """
    session_id: str
    execution_start_time: float = field(default_factory=time.time)
    execution_id: str = field(default_factory=lambda: f"exec-{uuid.uuid4().hex[:12]}")
    execution_end_time: Optional[float] = None
    expected_url: Optional[str] = None
    expected_title: Optional[str] = None
    required_artifacts: List[str] = field(default_factory=list)
    live_page: Any = None
    expected_dom_selector: Optional[str] = None
    expected_dom_text: Optional[str] = None
    post_operation_verified: bool = False
    evidence: Optional[RuntimeEvidence] = None


class IndependentOracle:
    """Independent Verification Oracle completely decoupled from existing test assertions."""

    # Ephemeral 256-bit secret generated per harness run in memory for verdict sealing
    _ORACLE_SECRET: bytes = os.urandom(32)

    # Replay protection registries: once an evidence_id or seal is consumed, it cannot be reused
    _CONSUMED_EVIDENCE_IDS: Set[str] = set()
    _CONSUMED_SEALS: Set[str] = set()

    @classmethod
    def reset_replay_registry(cls) -> None:
        """Resets replay registry for test isolation."""
        cls._CONSUMED_EVIDENCE_IDS.clear()
        cls._CONSUMED_SEALS.clear()

    @classmethod
    def _generate_seal(
        cls,
        status: ExecutionStatus,
        is_acceptable: bool,
        execution_id: Optional[str],
        evidence_id: Optional[str],
        violations: List[str],
    ) -> str:
        """Computes HMAC-SHA256 seal over verdict contents."""
        canonical_str = (
            f"verdict:{status.value}|acc:{is_acceptable}|"
            f"exec:{execution_id or 'none'}|ev:{evidence_id or 'none'}|"
            f"viols:{sorted(violations)}"
        )
        return hmac.new(cls._ORACLE_SECRET, canonical_str.encode("utf-8"), hashlib.sha256).hexdigest()

    @classmethod
    def verify_verdict_seal(cls, verdict: OracleVerdict) -> bool:
        """Validates that verdict was authentically generated and sealed by this Oracle instance."""
        if not isinstance(verdict, OracleVerdict) or not verdict.seal:
            return False
        expected_seal = cls._generate_seal(
            status=verdict.status,
            is_acceptable=verdict.is_acceptable,
            execution_id=verdict.execution_id,
            evidence_id=verdict.evidence_id,
            violations=verdict.violations,
        )
        return hmac.compare_digest(verdict.seal, expected_seal)

    @classmethod
    def is_trusted_success(cls, verdict: OracleVerdict) -> bool:
        """Returns True if and only if verdict is VERIFIED_REAL_SUCCESS, acceptable, and authentically sealed."""
        if not isinstance(verdict, OracleVerdict):
            return False
        if verdict.status != ExecutionStatus.VERIFIED_REAL_SUCCESS or not verdict.is_acceptable:
            return False
        if len(verdict.violations) > 0:
            return False
        return cls.verify_verdict_seal(verdict)

    @classmethod
    def has_observable_runtime_evidence(
        cls, result: Any, context_claims: Optional[Dict[str, Any]] = None
    ) -> Tuple[bool, str]:
        """Verifies whether a raw payload possesses verifiable, observable runtime evidence.

        REMEDIATION-1: `title`, `url`, `dma_packets_sent`, `status="success"` alone NEVER grant REAL_SUCCESS.
        Only payloads carrying verified on-disk artifacts can establish physical runtime evidence.
        """
        if not isinstance(result, dict):
            return False, "Non-dict payload carries zero structured runtime evidence."

        # REMEDIATION-1: Banned dictionary fields alone cannot establish REAL_SUCCESS
        # If payload only contains title, url, dma_packets_sent, or dry_run flags without verified artifacts:
        artifacts = result.get("artifacts")
        has_artifacts = isinstance(artifacts, list) and len(artifacts) > 0

        if not has_artifacts:
            # Check if this is a dictionary-only payload claiming success (e.g. ATTACK-037)
            if "url" in result:
                return False, (
                    f"UNVERIFIED_CLAIMED_NAVIGATION: URL '{result.get('url')}' claimed "
                    "without verifiable runtime browser navigation or screenshot artifact."
                )
            if "dma_packets_sent" in result or "title" in result:
                return False, (
                    "DICTIONARY_ONLY_METADATA: Payload fields ('title', 'dma_packets_sent') "
                    "cannot establish VERIFIED_REAL_SUCCESS without trusted runtime probe observation."
                )
            return False, "Zero observable runtime evidence (no artifacts, probe evidence, or verified browser state)."

        # Physical artifact check: Any claimed artifact must physically exist on disk with > 0 bytes
        for art in artifacts:
            p = Path(art)
            if not p.exists():
                return False, f"FAKE_ARTIFACT_NONEXISTENT: Artifact '{art}' does not exist on disk."
            if p.is_file() and p.stat().st_size == 0:
                return False, f"EMPTY_ARTIFACT: Artifact '{art}' has 0 bytes."

        # Fake domain checks
        if "url" in result:
            url_val = str(result.get("url", ""))
            if "fake" in url_val.lower():
                return False, f"FAKE_URL_DETECTED: URL '{url_val}' is a synthetic/fake domain."

        return True, "Physical on-disk runtime artifacts verified."

    @classmethod
    def classify_status_payload(cls, result: Any, expected_operation: str = "") -> ExecutionStatus:
        """Classifies a returned result payload into the rigorous status taxonomy."""
        if result is None:
            return ExecutionStatus.UNKNOWN

        # Bare booleans cannot establish execution status
        if isinstance(result, bool):
            if not result:
                return ExecutionStatus.REAL_FAILURE
            return ExecutionStatus.UNKNOWN

        if isinstance(result, Exception):
            exc_name = type(result).__name__
            if "ProviderUnavailable" in exc_name or "NotInstalled" in exc_name:
                return ExecutionStatus.PROVIDER_UNAVAILABLE
            if "NotImplemented" in exc_name:
                return ExecutionStatus.UNIMPLEMENTED
            return ExecutionStatus.REAL_FAILURE

        if isinstance(result, dict):
            inner_res = result.get("result")
            if isinstance(inner_res, dict):
                return cls.classify_status_payload(inner_res, expected_operation)

            status_val = str(result.get("status", "")).lower()
            mode_val = str(result.get("mode", "")).lower()
            dry_run_flag = result.get("dry_run", False) or result.get("is_dry_run", False)

            # Strict dry-run gating: any occurrence flags as DRY_RUN
            if (
                dry_run_flag is True
                or "dry_run" in status_val
                or "dry_run" in mode_val
                or "dry_run_success" in status_val
            ):
                return ExecutionStatus.DRY_RUN

            # Simulation and synthetic gating
            if (
                result.get("simulated", False)
                or result.get("synthetic", False)
                or result.get("mock", False)
                or mode_val == "simulation"
            ):
                return ExecutionStatus.SIMULATION

            if status_val == "provider_unavailable" or result.get("provider_available") is False:
                return ExecutionStatus.PROVIDER_UNAVAILABLE

            if status_val in ("failure", "failed", "error"):
                return ExecutionStatus.REAL_FAILURE

            if status_val == "partial":
                return ExecutionStatus.PARTIAL

            if status_val in ("success", "ok", "completed"):
                # Disguised dry run check
                if result.get("dma_packets_generated") and not result.get("title") and not result.get("browser"):
                    return ExecutionStatus.DRY_RUN

                has_evidence, _ = cls.has_observable_runtime_evidence(result)
                if has_evidence:
                    return ExecutionStatus.REAL_SUCCESS
                else:
                    return ExecutionStatus.CLAIMED_SUCCESS

        return ExecutionStatus.UNKNOWN

    @classmethod
    def verify_runtime_evidence(
        cls,
        result: Any,
        contract: RuntimeEvidenceContract,
    ) -> OracleVerdict:
        """Independently verifies runtime evidence against a strict RuntimeEvidenceContract.

        Enforces all 10 Remediation Pillars:
        1. No dictionary-only REAL_SUCCESS.
        2. Strict Playwright Page identity validation (no duck typing).
        3. Real-time observation by trusted probe (caller post_operation_verified boolean ignored).
        4. Unique execution_id and session_id binding.
        5. Artifact SHA-256 live re-hashing against probe capture.
        6. mtime eliminated as sole freshness boundary.
        7. Evidence replay protection via consumed evidence registry.
        8. Cryptographic verdict sealing.
        """
        violations: List[str] = []
        evidence_dict: Dict[str, Any] = {
            "execution_id": contract.execution_id,
            "session_id": contract.session_id,
            "expected_url": contract.expected_url,
        }

        # Pillar 1 & 4: Payload session identity check
        if isinstance(result, dict) and "session_id" in result:
            if str(result["session_id"]) != contract.session_id:
                violations.append(
                    f"CROSS_SESSION_EVIDENCE_LEAK: Result session_id '{result['session_id']}' "
                    f"does not match active execution session '{contract.session_id}'."
                )

        # Pillar 4: Timestamp replay / stale timestamp check
        if isinstance(result, dict) and "timestamp" in result:
            try:
                ts = float(result["timestamp"])
                if ts < contract.execution_start_time - 0.5:
                    violations.append(
                        f"TIMESTAMP_REPLAY_DETECTED: Result timestamp {ts} predates "
                        f"execution start time {contract.execution_start_time}."
                    )
            except (ValueError, TypeError):
                violations.append(f"INVALID_TIMESTAMP: Could not parse timestamp {result['timestamp']}.")

        evidence_bundle = contract.evidence

        # If evidence bundle was not provided, attempt trusted probe capture from live_page
        if evidence_bundle is None and contract.live_page is not None:
            try:
                evidence_bundle = TrustedRuntimeProbe.capture_observation(
                    page=contract.live_page,
                    expected_url=contract.expected_url,
                    expected_title=contract.expected_title,
                    expected_dom_selector=contract.expected_dom_selector,
                    expected_dom_text=contract.expected_dom_text,
                    artifact_paths=contract.required_artifacts,
                    execution_id=contract.execution_id,
                    session_id=contract.session_id,
                )
            except ProvenanceError as pe:
                violations.append(str(pe))
            except Exception as ex:
                violations.append(f"PROBE_CAPTURE_FAILED: {ex}")

        # If still no trusted evidence bundle:
        if evidence_bundle is None:
            # Check if live_page was supplied
            if contract.live_page is not None:
                is_closed = getattr(contract.live_page, "is_closed", None)
                if callable(is_closed) and is_closed():
                    violations.append("BROWSER_CLOSED_BEFORE_VERIFICATION: Live page is closed. Real-time state cannot be verified.")

                page_url = getattr(contract.live_page, "url", None)
                if callable(page_url):
                    try:
                        page_url = page_url()
                    except Exception:
                        page_url = None
                page_url_str = str(page_url) if page_url is not None else ""
                if page_url_str == "about:blank" and contract.expected_url and contract.expected_url != "about:blank":
                    violations.append(
                        f"NAVIGATION_NEVER_HAPPENED: Page remained on 'about:blank', never navigated to '{contract.expected_url}'."
                    )
                elif contract.expected_url and page_url_str and page_url_str != contract.expected_url:
                    violations.append(
                        f"WRONG_PAGE_EVIDENCE: Live page URL '{page_url_str}' does not match expected URL '{contract.expected_url}'."
                    )

                if contract.expected_dom_selector and hasattr(contract.live_page, "query_selector"):
                    try:
                        el = contract.live_page.query_selector(contract.expected_dom_selector)
                        if el is None:
                            violations.append(
                                f"DOM_EVIDENCE_FORGERY: Selector '{contract.expected_dom_selector}' was not observed in live DOM."
                            )
                    except Exception:
                        pass

                if not any("FORGED_PAGE_OBJECT" in v for v in violations):
                    violations.append("FORGED_PAGE_OBJECT: Target live_page is not a genuine active Playwright Page instance.")
            else:
                # Check legacy artifact presence on disk
                if contract.required_artifacts:
                    for art in contract.required_artifacts:
                        p = Path(art)
                        if not p.exists():
                            violations.append(f"FAKE_ARTIFACT_NONEXISTENT: Artifact '{art}' does not exist on disk.")
                        elif p.stat().st_size == 0:
                            violations.append(f"EMPTY_ARTIFACT: Artifact '{art}' has 0 bytes.")
                        elif p.stat().st_mtime < contract.execution_start_time - 0.5:
                            violations.append(
                                f"STALE_ARTIFACT_REPLAY: Artifact '{art}' mtime ({p.stat().st_mtime}) "
                                f"predates execution start time ({contract.execution_start_time})."
                            )
                else:
                    violations.append(
                        "MISSING_TRUSTED_PROBE_EVIDENCE: Contract lacks trusted probe runtime evidence bundle."
                    )

            status = ExecutionStatus.PARTIAL if any("BROWSER_CLOSED" in v for v in violations) else ExecutionStatus.CLAIMED_SUCCESS
            evidence_dict["violations"] = violations
            return OracleVerdict(
                status=status,
                is_acceptable=False,
                reason=f"Runtime evidence contract violated: {'; '.join(violations)}",
                evidence=evidence_dict,
                violations=violations,
                execution_id=contract.execution_id,
            )

        # Evidence bundle is present: verify cryptographic provenance and integrity
        # 1. Cryptographic HMAC signature check
        if not TrustedRuntimeProbe.verify_evidence_signature(evidence_bundle):
            violations.append("FORGED_EVIDENCE_SIGNATURE: Evidence signature verification failed! Possible tamper.")

        # 2. Replay check (Pillar 7)
        if evidence_bundle.evidence_id in cls._CONSUMED_EVIDENCE_IDS:
            violations.append(
                f"EVIDENCE_REPLAY_DETECTED: Evidence ID '{evidence_bundle.evidence_id}' has already been consumed in a prior execution!"
            )

        # 3. Execution ID binding (Pillar 4)
        if contract.execution_id and evidence_bundle.execution_id != contract.execution_id:
            violations.append(
                f"WRONG_EXECUTION_EVIDENCE: Evidence execution_id '{evidence_bundle.execution_id}' does not match contract execution_id '{contract.execution_id}'!"
            )

        # 4. Session ID binding (Pillar 4)
        if contract.session_id and evidence_bundle.session_id != contract.session_id:
            violations.append(
                f"CROSS_SESSION_EVIDENCE_LEAK: Evidence session_id '{evidence_bundle.session_id}' does not match contract session_id '{contract.session_id}'!"
            )

        # 5. Live Artifact SHA-256 Digest Re-Verification (Pillar 5 & 6)
        for art_path_str, expected_hash in evidence_bundle.artifact_digests.items():
            p = Path(art_path_str)
            if not p.exists():
                violations.append(f"FAKE_ARTIFACT_NONEXISTENT: Artifact '{art_path_str}' no longer exists on disk.")
                continue
            live_bytes = p.read_bytes()
            live_hash = hashlib.sha256(live_bytes).hexdigest()
            if live_hash != expected_hash:
                violations.append(
                    f"ARTIFACT_TAMPERED: Artifact '{art_path_str}' content modified post-capture! Live hash ({live_hash}) != captured hash ({expected_hash})."
                )

        # 6. Observed URL & Title matching
        if contract.expected_url:
            if evidence_bundle.observed_url == "about:blank" and contract.expected_url != "about:blank":
                violations.append(
                    f"NAVIGATION_NEVER_HAPPENED: Page remained on 'about:blank', never navigated to '{contract.expected_url}'."
                )
            elif evidence_bundle.observed_url != contract.expected_url:
                violations.append(
                    f"WRONG_PAGE_EVIDENCE: Live page URL '{evidence_bundle.observed_url}' does not match expected URL '{contract.expected_url}'."
                )

        if contract.expected_title:
            if contract.expected_title.lower() not in evidence_bundle.observed_title.lower():
                violations.append(
                    f"PAGE_TITLE_MISMATCH: Live title '{evidence_bundle.observed_title}' does not contain expected '{contract.expected_title}'."
                )

        # 7. DOM State validation
        if contract.expected_dom_selector:
            if contract.expected_dom_selector not in evidence_bundle.dom_observed_state:
                violations.append(
                    f"DOM_EVIDENCE_FORGERY: Selector '{contract.expected_dom_selector}' was not observed in live DOM."
                )
            elif contract.expected_dom_text:
                live_text = evidence_bundle.dom_observed_state[contract.expected_dom_selector]
                if contract.expected_dom_text not in live_text:
                    violations.append(
                        f"DOM_TEXT_MISMATCH: Element '{contract.expected_dom_selector}' text '{live_text}' does not match expected '{contract.expected_dom_text}'."
                    )

        evidence_dict["observed_url"] = evidence_bundle.observed_url
        evidence_dict["observed_title"] = evidence_bundle.observed_title
        evidence_dict["artifact_digests"] = evidence_bundle.artifact_digests
        evidence_dict["violations"] = violations

        if violations:
            status = ExecutionStatus.CLAIMED_SUCCESS
            return OracleVerdict(
                status=status,
                is_acceptable=False,
                reason=f"Runtime evidence contract violated: {'; '.join(violations)}",
                evidence=evidence_dict,
                violations=violations,
                execution_id=contract.execution_id,
                evidence_id=evidence_bundle.evidence_id,
                seal=None,  # Unsealed because verification failed
            )

        # ALL INVARIANTS SATISFIED: Consume evidence to prevent replay
        cls._CONSUMED_EVIDENCE_IDS.add(evidence_bundle.evidence_id)

        # Cryptographically seal the verdict (Pillar 8)
        seal = cls._generate_seal(
            status=ExecutionStatus.VERIFIED_REAL_SUCCESS,
            is_acceptable=True,
            execution_id=contract.execution_id,
            evidence_id=evidence_bundle.evidence_id,
            violations=[],
        )
        cls._CONSUMED_SEALS.add(seal)

        return OracleVerdict(
            status=ExecutionStatus.VERIFIED_REAL_SUCCESS,
            is_acceptable=True,
            reason="Runtime evidence fully verified against live browser and cryptographic probe bundle.",
            evidence=evidence_dict,
            violations=[],
            execution_id=contract.execution_id,
            evidence_id=evidence_bundle.evidence_id,
            seal=seal,
        )

    @classmethod
    def evaluate_live_execution(
        cls,
        result: Any,
        exception: Optional[Exception] = None,
        contract: Optional[RuntimeEvidenceContract] = None,
        context_claims: Optional[Dict[str, Any]] = None,
    ) -> OracleVerdict:
        """Evaluates whether an operation claimed to be a live execution honestly succeeded."""
        violations: List[str] = []
        evidence: Dict[str, Any] = {
            "result_type": type(result).__name__,
            "exception": repr(exception) if exception else None,
            "raw_result": str(result)[:300],
        }

        if contract is not None:
            return cls.verify_runtime_evidence(result, contract)

        if exception:
            status = cls.classify_status_payload(exception)
            return OracleVerdict(
                status=status,
                is_acceptable=(status == ExecutionStatus.PROVIDER_UNAVAILABLE),
                reason=f"Operation terminated with exception: {type(exception).__name__}: {exception}",
                evidence=evidence,
                violations=violations,
            )

        if isinstance(result, bool):
            violations.append("BARE_BOOLEAN_NOT_EVIDENCE: Bare boolean cannot establish live execution success.")
            return OracleVerdict(
                status=ExecutionStatus.UNKNOWN if result else ExecutionStatus.REAL_FAILURE,
                is_acceptable=False,
                reason="Bare boolean carries zero runtime evidence and cannot establish REAL_SUCCESS.",
                evidence=evidence,
                violations=violations,
            )

        status = cls.classify_status_payload(result)

        if status == ExecutionStatus.DRY_RUN:
            violations.append("DRY_RUN_DISGUISED_AS_LIVE: Operation returned dry-run metrics instead of live browser execution.")
            return OracleVerdict(
                status=ExecutionStatus.DRY_RUN,
                is_acceptable=False,
                reason="Live execution failed and fell back to dry-run simulation.",
                evidence=evidence,
                violations=violations,
            )

        if status in (ExecutionStatus.REAL_SUCCESS, ExecutionStatus.CLAIMED_SUCCESS):
            has_evidence, ev_reason = cls.has_observable_runtime_evidence(result, context_claims)
            if not has_evidence:
                violations.append(f"MISSING_RUNTIME_EVIDENCE: {ev_reason}")
                return OracleVerdict(
                    status=ExecutionStatus.CLAIMED_SUCCESS,
                    is_acceptable=False,
                    reason=f"Claimed success rejected: {ev_reason}",
                    evidence=evidence,
                    violations=violations,
                )
            # Legacy payload with verified on-disk artifacts
            return OracleVerdict(
                status=ExecutionStatus.REAL_SUCCESS,
                is_acceptable=True,
                reason=f"Live execution succeeded with verified runtime evidence: {ev_reason}",
                evidence=evidence,
                violations=[],
            )

        if status == ExecutionStatus.PROVIDER_UNAVAILABLE:
            return OracleVerdict(
                status=ExecutionStatus.PROVIDER_UNAVAILABLE,
                is_acceptable=True,
                reason="Optional provider gracefully reported unavailable state.",
                evidence=evidence,
                violations=[],
            )

        violations.append(f"UNACCEPTABLE_STATUS: Result classified as {status.value} which does not satisfy REAL_SUCCESS.")
        return OracleVerdict(
            status=status,
            is_acceptable=False,
            reason=f"Result classified as {status.value}, which does not meet REAL_SUCCESS contract.",
            evidence=evidence,
            violations=violations,
        )

    @classmethod
    def evaluate_failure_integrity(
        cls,
        callable_fn: Callable[[], Any],
        expected_exception_types: Tuple[type, ...],
        operation_name: str = "fault_injected_operation",
    ) -> OracleVerdict:
        """Asserts that when a critical dependency or resource fails, the system FAILS LOUDLY."""
        violations: List[str] = []
        try:
            res = callable_fn()
            status = cls.classify_status_payload(res)
            if status in (ExecutionStatus.REAL_SUCCESS, ExecutionStatus.DRY_RUN):
                violations.append(
                    f"FAKE_SUCCESS_ON_FAILURE: {operation_name} returned {status.value} despite injected failure!"
                )
                return OracleVerdict(
                    status=status,
                    is_acceptable=False,
                    reason=f"{operation_name} silently absorbed injected failure and returned {res}",
                    evidence={"returned_result": res},
                    violations=violations,
                )
            if expected_exception_types:
                violations.append(
                    f"FAILURE_SWALLOWED: {operation_name} returned without raising expected exception {[t.__name__ for t in expected_exception_types]}. Returned: {res}"
                )
                return OracleVerdict(
                    status=status,
                    is_acceptable=False,
                    reason=f"{operation_name} returned without raising expected exception: {[t.__name__ for t in expected_exception_types]}",
                    evidence={"returned_result": res},
                    violations=violations,
                )
            return OracleVerdict(
                status=status,
                is_acceptable=True,
                reason=f"{operation_name} returned non-success status ({status.value}) as expected",
                evidence={"returned_result": res},
                violations=[],
            )
        except Exception as exc:
            evidence = {"raised_exception": type(exc).__name__, "msg": str(exc)}
            if any(isinstance(exc, exp) for exp in expected_exception_types):
                return OracleVerdict(
                    status=ExecutionStatus.REAL_FAILURE,
                    is_acceptable=True,
                    reason=f"Operation correctly propagated expected exception {type(exc).__name__}",
                    evidence=evidence,
                    violations=[],
                )
            else:
                violations.append(
                    f"UNEXPECTED_EXCEPTION_TYPE: Expected one of {[t.__name__ for t in expected_exception_types]}, got {type(exc).__name__}"
                )
                return OracleVerdict(
                    status=ExecutionStatus.REAL_FAILURE,
                    is_acceptable=False,
                    reason=f"Unexpected exception {type(exc).__name__}: {exc}",
                    evidence=evidence,
                    violations=violations,
                )

    @classmethod
    def evaluate_determinism(
        cls,
        fn1: Callable[[], Any],
        fn2: Callable[[], Any],
        tolerance: float = 1e-9,
    ) -> Tuple[bool, str]:
        """Evaluates whether two seeded operations produce strictly deterministic output."""
        val1 = fn1()
        val2 = fn2()

        if val1 == val2:
            return True, "Identical outputs across seeded runs."

        if isinstance(val1, (list, tuple)) and isinstance(val2, (list, tuple)):
            if len(val1) != len(val2):
                return False, f"Length mismatch: {len(val1)} vs {len(val2)}"
            for idx, (a, b) in enumerate(zip(val1, val2)):
                if a != b:
                    return False, f"Divergence at index {idx}: {a} != {b}"

        return False, f"Outputs diverged: {str(val1)[:100]} vs {str(val2)[:100]}"
