"""
Typing.Protocol structural interfaces for dependency injection and mocking.
"""

from typing import Any, Dict, List, Optional, Protocol, Tuple, runtime_checkable


@runtime_checkable
class RandomSource(Protocol):
    """Structural interface abstracting randomness generations to decouple test pipelines with Advanced Physics Distributions."""

    def uniform(self, a: float, b: float) -> float: ...
    def gauss(self, mu: float, sigma: float) -> float: ...
    def random(self) -> float: ...
    def choice(self, seq: Any) -> Any: ...
    def weibull(self, alpha: float, beta: float) -> float: ...
    def beta(self, a: float, b: float) -> float: ...
    def gamma(self, alpha: float, beta: float) -> float: ...


@runtime_checkable
class Clock(Protocol):
    """Structural interface abstracting asynchronous delay mechanisms for temporal control."""

    async def sleep(self, seconds: float) -> None: ...
    def time(self) -> float: ...


@runtime_checkable
class MouseProtocol(Protocol):
    async def move(self, x: float, y: float) -> None: ...
    async def down(self) -> None: ...
    async def up(self) -> None: ...
    async def wheel(self, delta_x: float, delta_y: float) -> None: ...


@runtime_checkable
class KeyboardProtocol(Protocol):
    async def type(self, text: str, delay: Optional[float] = None) -> None: ...
    async def press(self, key: str) -> None: ...


@runtime_checkable
class ElementHandleProtocol(Protocol):
    async def bounding_box(self) -> Optional[Dict[str, float]]: ...


@runtime_checkable
class PageProtocol(Protocol):
    @property
    def mouse(self) -> MouseProtocol: ...
    @property
    def keyboard(self) -> KeyboardProtocol: ...
    @property
    def url(self) -> str: ...
    async def evaluate(self, script: str, *args: Any) -> Any: ...
    async def wait_for_selector(
        self, selector: str, state: Optional[str] = None, timeout: Optional[float] = None
    ) -> Optional[ElementHandleProtocol]: ...
    async def goto(self, url: str, wait_until: Optional[str] = None, timeout: Optional[float] = None) -> Any: ...
    async def title(self) -> str: ...
    async def screenshot(self, path: Optional[str] = None) -> Any: ...


@runtime_checkable
class BrowserContextProtocol(Protocol):
    @property
    def pages(self) -> List[PageProtocol]: ...
    async def new_page(self) -> PageProtocol: ...
    async def close(self) -> None: ...
    async def add_init_script(self, script: str) -> None: ...


@runtime_checkable
class BrowserProtocol(Protocol):
    async def close(self) -> None: ...


@runtime_checkable
class BrowserProvider(Protocol):
    """Interface orchestrating underlying browser lifecycle configurations."""

    async def launch_context(self) -> Tuple[BrowserContextProtocol, Optional[BrowserProtocol]]: ...
    async def shutdown(self) -> None: ...


@runtime_checkable
class ChallengeSolverProtocol(Protocol):
    async def solve(self, page: PageProtocol, challenge_type: str) -> bool: ...
